---
get:
  name: shared_ecr_prd
  path: awsma?region=us-east-1
kind: secret
name: ecr-creds
---
kind: pipeline
type: docker
name: check-code

steps:
  - image: us.gcr.io/nyt-registry-prd/drone-awsma-decode-creds
    name: decode-creds
    settings:
      encoded_creds:
        from_secret: ecr-creds
      export_creds_location: .export_creds_development
      shared_creds_location: .shared_creds_development

  - name: run-tests
    image: golang:1.23
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go build -a -ldflags "-X main.version=${DRONE_TAG} -X main.rev=${DRONE_COMMIT}"
      - go test ./...

  - name: go-build
    image: golang:1.23
    commands:
      - sh scripts/build.sh
    depends_on:
      - run-tests

  - image: plugins/ecr
    name: image-build-dry-run
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /drone/src/.shared_creds_development
    settings:
      dry_run: true
      context: .
      dockerfile: ./docker/Dockerfile.linux.amd64
      registry: 375574098923.dkr.ecr.us-east-1.amazonaws.com
      repo: drone-convert-pathschanged/drone-convert-pathschanged
      tags:
        - test
    depends_on:
      - decode-creds
      - go-build

---
kind: pipeline
type: docker
name: publish-to-ecr-unstable

trigger:
  event:
    - push
  branch:
    - main

depends_on:
  - check-code

steps:
  - image: us.gcr.io/nyt-registry-prd/drone-awsma-decode-creds
    name: decode-creds
    settings:
      encoded_creds:
        from_secret: ecr-creds
      export_creds_location: .export_creds_development
      shared_creds_location: .shared_creds_development

  - name: go-build
    image: golang:1.23
    commands:
      - sh scripts/build.sh

  - name: image-build-publish-unstable
    image: plugins/ecr
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /drone/src/.shared_creds_development
    settings:
      context: .
      dockerfile: ./docker/Dockerfile.linux.amd64
      registry: 375574098923.dkr.ecr.us-east-1.amazonaws.com
      repo: drone-convert-pathschanged
      tags:
        - unstable
        - ${DRONE_COMMIT:0:7}
    depends_on:
      - go-build
      - decode-creds
    when:
      ref:
        exclude:
          - refs/tags/*
      branch:
        - main
---
kind: pipeline
type: docker
name: publish-to-ecr-stable

trigger:
  event:
    - tag

depends_on:
  - check-code

steps:
  - image: us.gcr.io/nyt-registry-prd/drone-awsma-decode-creds
    name: decode-creds
    settings:
      encoded_creds:
        from_secret: ecr-creds
      export_creds_location: .export_creds_development
      shared_creds_location: .shared_creds_development

  - name: go-build
    image: golang:1.23
    commands:
      - sh scripts/build.sh

  - name: build_publish_stable
    image: plugins/ecr
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /drone/src/.shared_creds_development
    settings:
      context: .
      dockerfile: ./docker/Dockerfile.linux.amd64
      registry: 375574098923.dkr.ecr.us-east-1.amazonaws.com
      repo: drone-convert-pathschanged
      tags:
        - stable
        - ${DRONE_TAG}
      build_args_from_env:
        - DRONE_TAG
    depends_on:
      - go-build
      - decode-creds